adminUser:
  password: vault:ckrych4/adminUser:password
  username: corinnekrych
enableDocker: false
pipelineUser:
  email: corinnekrych@gmail.com
  token: vault:ckrych4/pipelineUser:token
  username: corinnekrych
prow:
  hmacToken: vault:ckrych4/prow:hmacToken
